import type { NextPage } from "next";

import { useEffect, useState } from "react";
import Head from "next/head";

import { Dashboard, LoginForm } from "ui";

type Token = string | null;

const Home: NextPage = () => {
  const [authenticationToken, setAuthenticationToken] = useState<Token>("");

  const login = (token: string) => {
    if (!token) return;

    setAuthenticationToken(token);
    localStorage.setItem("authenticationToken", token);
  };

  const logout = () => {
    setAuthenticationToken(null);
    localStorage.removeItem("authenticationToken");
  };

  useEffect(() => {
    const storageToken = localStorage.getItem("authenticationToken");

    if (storageToken) setAuthenticationToken(storageToken);
  }, [setAuthenticationToken]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {authenticationToken ? (
          <Dashboard token={authenticationToken} logout={logout} />
        ) : (
          <LoginForm login={login} />
        )}
      </main>
    </>
  );
};

export default Home;
