name: Vercel Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy application"

    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          BUILD_ENV: |
            NEXT_PUBLIC_APP_STAGE=LIVE
            AWS_REGION=eu-central-1
            AWS_ACCESS_KEY_ID=${{ secrets.ENV_AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
            AWS_DYNAMODB_TABLE=substitutions-live
            ADMIN_LOGIN_EMAIL=${{ secrets.ENV_ADMIN_LOGIN_EMAIL }}
            ADMIN_LOGIN_PASSWORD=${{ secrets.ENV_ADMIN_LOGIN_PASSWORD }}
            ADMIN_LOGIN_TOKEN=${{ secrets.ENV_ADMIN_LOGIN_TOKEN }}
            SENTRY_IGNORE_API_RESOLUTION_ERROR=1
