name: Heroku Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Heroku

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: kfg-substitutions-demo
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: main
        env:
          HD_NEXT_PUBLIC_STAGE: "LIVE"
          HD_NEXT_PUBLIC_API_BASE_URL: ${{secrets.ENV_NEXT_PUBLIC_API_BASE_URL}}

          HD_AWS_REGION: "eu-central-1"
          HD_AWS_ACCESS_KEY_ID: ${{secrets.ENV_AWS_ACCESS_KEY_ID}}
          HD_AWS_SECRET_ACCESS_KEY: ${{secrets.ENV_AWS_SECRET_ACCESS_KEY}}

          HD_AWS_DYNAMODB_TABLE: "substitutions-live"

          HD_ADMIN_LOGIN_EMAIL: ${{secrets.ENV_ADMIN_LOGIN_EMAIL}}
          HD_ADMIN_LOGIN_PASSWORD: ${{secrets.ENV_ADMIN_LOGIN_PASSWORD}}
          HD_ADMIN_LOGIN_TOKEN: ${{secrets.ENV_ADMIN_LOGIN_TOKEN}}

          SENTRY_IGNORE_API_RESOLUTION_ERROR: 1
